# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin
kotlin.code.style=official

# AndroidX
android.useAndroidX=true

# Fix l?i Built-in Kotlin + KSP
android.disallowKotlinSourceSets=false

# T?ng performance
android.dependency.excludeLibraryComponentsFromConstraints=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false

# Các setting khác
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false